source ~/.vim/plugins.vim

set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set autoindent
set smartindent

set colorcolumn=81,121

set number

set termguicolors
colorscheme base16-material-darker
set background=dark

set nobackup
set nowritebackup
set noswapfile

set backspace=indent,eol,start
set mouse=a

set updatetime=100

"" Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"" Airline Configuration
let g:airline_theme='base16'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

"" NERDTree Configuration
" Always show nerdtree
autocmd vimenter * NERDTree | wincmd p
let g:NERDTreeWinSize=50
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"" COC Configuration
set completeopt-=preview
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>"
