format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.jj}\
$python\
$aws\
$line_break\
$jobs\
$character"""

[hostname]
ssh_only = true

[username]
show_always = false

[jobs]
number_threshold = 1

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[custom.jj]
command = '''
jj log --revisions @ --limit 1 --ignore-working-copy --no-graph --color always  --template '
  separate(" ",
    if(bookmarks, ""),
    change_id.shortest(8),
    if(empty, "(empty)"),
    truncate_end(100, description.first_line(), "…"),
    if(conflict, "💥"),
  )
'
'''
when = "jj --ignore-working-copy root"
symbol = "🥋 "
