format = """
$username\
$hostname\
$directory\
${custom.jj}\
$python\
$line_break\
$jobs\
$character"""

[hostname]
ssh_only = true

[username]
show_always = false

[jobs]
number_threshold = 1

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--no-symbol", "--bookmarks-display-limit", "1"]
format = "$output "
